# Generated by Django 4.1.7 on 2023-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_url', models.CharField(max_length=200, unique=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('actor', models.ManyToManyField(related_name='movie', to='movie.actor')),
                ('director', models.ManyToManyField(related_name='director', to='movie.director')),
                ('genre', models.ManyToManyField(related_name='genre', to='movie.genre')),
            ],
        ),
    ]
