# Generated by Django 4.1.7 on 2023-04-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
